#!/usr/bin/perl
# 
#  Based on doc_display.cgi from /opt/carsi/modules/common/cgi
#

use strict;
use warnings;

my $directory = '/opt/samba/data_comp/vol00019/20/553620';
my $dirpath;
my $temppathname = '/opt/samba/data_comp/vol00019/20/553620/tmp';
my $outfilename;
my $filename;
my $magcookie;
my $majverno;
my $minverno;
my $numpage;
my $numcomp;
my $vbdirpos;
my $perldirpos;
my $len;
my $imfilenames;
my $imagefilename;
my $vbstartpos;
my $perlstartpos;
my $filelen;
my ($i,$j,$k);
my $blocksize;
my $numblocks;
my $partial_block_length;
my $partialbuff;
my $tiffbuff;

$dirpath = $ARGV[0] if (exists $ARGV[0]);

#  We want to read all image documents in the directory,
#  which have the suffix .000

opendir (DIR, $directory) or die $!;

while ($filename = readdir(DIR)) {

print "$filename\n";

	next if ($filename =~ m/^\./);
	&extract_files($filename);
}


closedir(DIR);

exit;

sub extract_files
{   
	#  Note!.  Opening two copies of document file so that can walk down the
	#  document file's internal directory at the same time that are walking down
	#  the image locations.  
	

		
	open(DOCFILE, '<', $filename) || die "Can't open doc1  $filename: $!\n";
	open(DOCFILE2, '<', $filename) || die "Can't open doc2 $filename: $!\n";
	
	$len = read(DOCFILE,$magcookie,8);
	$len = read(DOCFILE,$majverno,3);
	$len = read(DOCFILE,$minverno,3);
	$len = read(DOCFILE,$numpage,4);
	$len = read(DOCFILE,$numcomp,4);
	$len = read(DOCFILE,$vbdirpos,10);
	
	
#	print "magcookie $magcookie\n";
#	print "majverno $majverno\n";
#	print "minverno $minverno\n";
#	print "numpage $numpage\n";
#	print "numcomp $numcomp\n";
#	print "vbdirpos: $vbdirpos\n";
	
	$perldirpos = $vbdirpos -1;
		
	#    Seek to the beginning of the Document file's internal directory.
	
	seek(DOCFILE,$perldirpos,0);
	$imfilenames = "";       
	
	for ($i=0;$i<$numpage;$i++)
	{
		#   For each entry in the directory of the document, get the information
		#   for the corresponding image file.  This includes the filename to use,
		#   the start position in this document file, and the file length.
		
		$len = read(DOCFILE,$imagefilename,12);
		$len = read(DOCFILE,$vbstartpos,10);
		$perlstartpos = $vbstartpos - 1;
		$len = read(DOCFILE,$filelen,10);

		extract_image_file();   
       
	}
} 
#end - sub extract_files

sub extract_image_file
{       
	# This subroutine will use the implicit parameters $imagefilename, $startpos,
	# and $filelen to extract the selected image file from the document file.
	
	print "\n";
	print "Image number = ".($i+1)."|\n";
	print "Image name = ".$imagefilename."|\n";
#	print "File start position = ".$vbstartpos."|\n";
#	print "Start position = ".$perlstartpos."|\n";
	print "File length = ".$filelen."|\n";
	print "\n";
	my $quotient = $filelen/512;
	
	
	$numblocks = int($filelen/512);
	$partial_block_length = $filelen%512;    
	
#	print "Quotient = ".$quotient."|\n";
	print "Number of blocks = ".$numblocks."|\n";
	print "Length of last block = ".$partial_block_length."|\n";
	
	$outfilename = $temppathname. "/test.TIF";
	
	open (IMAGEFILE,">$outfilename") || die "Cannot open $outfilename: $!\n";
	
	seek(DOCFILE2,$perlstartpos,0);
	
	$k = 0;
	$blocksize = 512;
	for ($j=0;$j<$numblocks;$j++)
	{ 
		# First read and write all of the complete blocks
		
		$len = read(DOCFILE2, $tiffbuff, 512);
		print(IMAGEFILE $tiffbuff);
		$k = $j;
	}
	
	# Next read and write the partial block (if there is one)
	
	if ($partial_block_length > 0)
	{
		$len = read(DOCFILE2, $partialbuff, $partial_block_length);
		print(IMAGEFILE $partialbuff);
	}
	# Finished with this file so close it.
	close(IMAGEFILE);
} 
#end - sub extract_image_file

